// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtbupUUYAcPLvCanIair1UZSwcTyQ83CA',
    appId: '1:164089296966:web:e16ad8c8d296c9f9d43247',
    messagingSenderId: '164089296966',
    projectId: 'my-web-app-1eea7',
    authDomain: 'my-web-app-1eea7.firebaseapp.com',
    storageBucket: 'my-web-app-1eea7.firebasestorage.app',
    measurementId: 'G-H71T0RR7E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBDZM-HS_UUPdW-847LZJkdTJ5qVc3y9s',
    appId: '1:164089296966:android:3017261bc6a83743d43247',
    messagingSenderId: '164089296966',
    projectId: 'my-web-app-1eea7',
    storageBucket: 'my-web-app-1eea7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuKNNP9qVP7TMDLhRcKadQaG7PDBJsBso',
    appId: '1:164089296966:ios:89a21ce2b5dde11ed43247',
    messagingSenderId: '164089296966',
    projectId: 'my-web-app-1eea7',
    storageBucket: 'my-web-app-1eea7.firebasestorage.app',
    iosBundleId: 'com.example.myWebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuKNNP9qVP7TMDLhRcKadQaG7PDBJsBso',
    appId: '1:164089296966:ios:89a21ce2b5dde11ed43247',
    messagingSenderId: '164089296966',
    projectId: 'my-web-app-1eea7',
    storageBucket: 'my-web-app-1eea7.firebasestorage.app',
    iosBundleId: 'com.example.myWebApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtbupUUYAcPLvCanIair1UZSwcTyQ83CA',
    appId: '1:164089296966:web:97bf7926df025e89d43247',
    messagingSenderId: '164089296966',
    projectId: 'my-web-app-1eea7',
    authDomain: 'my-web-app-1eea7.firebaseapp.com',
    storageBucket: 'my-web-app-1eea7.firebasestorage.app',
    measurementId: 'G-LGF2JG5QM6',
  );

}